### ISSUE TITLE
One non-instantaneous strong branch in a cobegin should be enough

### ISSUE THREAD

**Issue by schorg** [boschresearch/blech#28]
Imagine the following activity

```
activity NotInstantaneous ()
    var x = 1: int32
    cobegin
        await true
    with weak
        x = 2
    end
end
```
The compiler complains about an instantaneous control path.

**Describe the bug**
But, the strong branch is not instantaneous and therefore the whole 
activity does not contain an instantaneous control path.

**Solution**
One non-instantaneous strong branch in a cobegin should make the whole cobegin non-instantaneous.
This means, the second branch could also be strong.

**Comment by FriedrichGretz** [comment]
I was about to find out what would be necessary to fix this and here is what our implementation says about this issue 

```
// we could allow instantaneous blocks whenever there is at least one
// strong block which delays - but this is complex to check and explain 
// to the user and seems fragile from a programmer's point of view
```

So currently a cobegin statement is considered delaying if all its branches delay or otherwise it is considered instantaneous if there is at least one instantaneous branch.

The proposed alternative would consider cobegin to be delaying if there is at least one strong delaying branch or all weak branches are delaying and otherwise instantaneous if there is no delaying strong branch.

We should carefully re-evaluate especially the last line saying "seems fragile from a programmer's point of view". Can we find examples supporting this claim or arguments to disprove it?

Also note that the current "bug" has a simple workaround: add `await true` at the end of the instantaneous branch. It will not change the behaviour of the program but satisfy the compiler.
