### ISSUE TITLE
Exposing a constants requires to expose all constants in subexpression

### ISSUE THREAD

**Issue by FriedrichGretz** [boschresearch/blech#63]
**Describe the bug**
This code
```
module exposes C

const A: nat8 = 4
const B: nat8 = 18 
const C = A * (B - 2)
```
fails to compile with the error message that B (and A) is less accessible than C.
However `const` expressions can be evaluated at compile time and so only the value 64 needs to be written to the signature not how it is calculated in the module.

**Expected behaviour**
Above code should compile without errors.

**Additional context**
Currently, `const` in Blech declares a compile time constant (aka `#define`) in C. If that changes due to complex types than the issue above might become more intricate.

**Comment by schorg** [comment]
This is not a bug - its a feature by design:

- Consts are regarded as transparent - they expose their internal structure, like a transparent type.
- Consts are compile time values - constant evaluation is an optimization.
- Not all `const`s can be evaluated at compile time - e. g. `extern const`
- All compile time values need to expose their internal structure in the signature - imagine compile-time functions, generic functions that must be monomorphised - in order to allow compile-time evaluation in the importing module.
- Compile-time evaluation should not change signatures.
